# Generated by Django 3.2 on 2021-11-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20211113_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='name',
            new_name='achievement_name',
        ),
    ]
