# Generated by Django 3.2 on 2021-11-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_rename_name_achievement_achievement_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='achievement_name',
            new_name='name',
        ),
    ]
